packages:
  - 'packages/*'

catalog:
  '@cocos/creator-types': '3.8.7'
  '@types/node': '^25.9.2'
  'typescript': '^6.0.3'
  'vite': '^8.2.2'
  'vitest': '^4.1.6'
  'vue-tsc': '^3.3.11'

autoInstallPeers: false

onlyBuiltDependencies:
  - esbuild

allowBuilds:
  esbuild: true
